In [1]:
%load_ext autoreload
%autoreload 2

In [15]:
import os

In [16]:
from process_video import load_video, get_phonems, load_data

In [17]:
path = "/Users/ArthurPech/Downloads/SilentSpeak/"
session = 'I'
locutor = 1
file = 1

In [19]:
frames, phonems = load_data(path, session, locutor, file)

In [20]:
frames

[<tf.Tensor: shape=(576, 720, 1), dtype=uint8, numpy=
 array([[[57],
         [60],
         [52],
         ...,
         [57],
         [60],
         [53]],
 
        [[53],
         [59],
         [57],
         ...,
         [55],
         [56],
         [54]],
 
        [[59],
         [61],
         [58],
         ...,
         [57],
         [58],
         [53]],
 
        ...,
 
        [[28],
         [31],
         [29],
         ...,
         [16],
         [16],
         [15]],
 
        [[27],
         [31],
         [29],
         ...,
         [15],
         [15],
         [11]],
 
        [[25],
         [26],
         [29],
         ...,
         [13],
         [15],
         [13]]], dtype=uint8)>,
 <tf.Tensor: shape=(576, 720, 1), dtype=uint8, numpy=
 array([[[57],
         [59],
         [59],
         ...,
         [59],
         [58],
         [55]],
 
        [[58],
         [59],
         [60],
         ...,
         [58],
         [57],
         [55]],
 
       

In [21]:
phonems

['m', 'a', 'S', 'deux', 'm', 'i', 'z', 'E', 'R', 'u', 's', 'i']